apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  {{- with .Values.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: "PathPrefix(`/`)"
      kind: Rule
      services:
      - name: {{ include "ui.fullname" . }}
        port: {{ .Values.service.port }}